Repository jiphyeonjeon-42/backend, pull requests merged in 2022-11, with the labels that each got.

#256 FEAT: 연체일이 지나면 하루에 한번씩 계속 알림
  backend/src/notifications/notifications.service.ts
Labels: proposal

#255 253 feat 도서 수정을 위한 api 보완요청
  backend/src/books/books.controller.ts
  backend/src/books/books.service.ts
  backend/src/books/entity/bookInfo.entity.ts
  backend/src/routes/books.routes.ts
Labels: documentation, enhancement, refactoring

#262 253 feat 도서 수정을 위한 api 보완요청
  backend/src/books/books.service.ts
  backend/src/routes/books.routes.ts
Labels: enhancement

#271 270 feat histories의 반환값 추가
  backend/src/histories/histories.service.ts
  backend/src/routes/histories.routes.ts
Labels: proposal
